server:
  port: 10000
  servlet:
    context-path: /api
zuul:
  routes:
    account-restapi:   #如果不配置默认根据服务名称映射
      path: /account/**
      serviceId: account-restapi
      strip-prefix: false  #保留前缀
    auth-server:   #如果不配置默认根据服务名称映射
      path: /uaa/**
      serviceId: auth-server
      strip-prefix: false  #保留前缀
    resource-server:   #如果不配置默认根据服务名称映射
      path: /resource/**
      serviceId: resource-server
      strip-prefix: false  #保留前缀
  # retryable: true #开启重试机制配合ribbon
  sensitive-headers: Cookie,Set-Cookie

ribbon: #超时设置
  ReadTimeout: 60000
  ConnectTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: ["*"]  #开启所有的端点监控，默认只开放info,health
