server:
  port: 8080
  servlet:
    context-path: /
zuul:
  routes:
    account-restapi:   #如果不配置默认根据服务名称映射
      path: /account/**
      serviceId: account-restapi
      strip-prefix: false  #保留前缀
    resource-server:   #如果不配置默认根据服务名称映射
      path: /resource/**
      serviceId: resource-server
      strip-prefix: false  #保留前缀
  # retryable: true #开启重试机制配合ribbon
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9999/uaa/oauth/token
      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
      client-id: zuul-server
      client-secret: secret #客户端秘钥
    resource:
      jwt:
        key-value: base-yhuk #对称加密，默认算法HS256
management:
  endpoints:
    web:
      exposure:
        include: ["*"]  #开启所有的端点监控，默认只开放info,health
