spring:
  application:
    name: resource-server
server:
  port: 7777
  servlet:
    context-path: /resource
eureka:
  client:
    service-url:
      defaultZone: http://123.207.255.184:8761/eureka/
  instance:
    appname: resource-server
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
    ip-address: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

